### ISSUE TITLE
Singularity container does not work due to read only filesystem

### ISSUE THREAD

**Issue by Shellfishgene** [NBISweden/GUESSmyLT#21]
Hi!
I tried the Singularity container, but get below error, Probably whatever that is should be extracted to a tempdir outside the container. Conda works for me.
```
singularity run -B $WORK:$WORK $WORK/singularity/guessmylt\:0.2.5--py_0.sif

Singularity> GUESSmyLT --reads foo_1.fq.gz foo_2.fq.gz --reference genome.fasta --annotation genomic.gff --organism euk
           
Traceback (most recent call last):
  File "/usr/local/bin/GUESSmyLT", line 6, in <module>        
    from GUESSmyLT.GUESSmyLT import main                           
  File "/usr/local/lib/python3.6/site-packages/GUESSmyLT/GUESSmyLT.py", line 29, in <module>
    tf.extractall(path=script_dir+"data/")                         
  File "/usr/local/lib/python3.6/tarfile.py", line 2010, in extractall
    numeric_owner=numeric_owner)                              
  File "/usr/local/lib/python3.6/tarfile.py", line 2052, in extract
    numeric_owner=numeric_owner)                              
  File "/usr/local/lib/python3.6/tarfile.py", line 2124, in _extract_member
    self.makedir(tarinfo, targetpath)
  File "/usr/local/lib/python3.6/tarfile.py", line 2153, in makedir
    os.mkdir(targetpath, 0o700)
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.6/site-packages/GUESSmyLT/data/eukaryota_odb9'
```

**Comment by Juke34** [comment]
Interesting, I don't know the best way to deal with that.
